export const elements = {
  body: (content, className) => `<body class="${className}">${content}</body>`,
  main: (content, className) => `<main class="${className}">${content}</main>`,
  header: (content, className) => `<header class="${className}">${content}</header>`,
  section: (content, className) => `<section class="${className}">${content}</section>`,
  article: (content, className) => `<article class="${className}">${content}</article>`,
  aside: (content, className) => `<aside class="${className}">${content}</aside>`,
  div: (content, className) => `<div class="${className}">${content}</div>`,
  span: (content, className) => `<span class="${className}">${content}</span>`,
  h1: (content, className) => `<h1 class="${className}">${content}</h1>`,
  h2: (content, className) => `<h2 class="${className}">${content}</h2>`,
  h3: (content, className) => `<h3 class="${className}">${content}</h3>`,
  h4: (content, className) => `<h4 class="${className}">${content}</h4>`,
  h5: (content, className) => `<h5 class="${className}">${content}</h5>`,
  h6: (content, className) => `<h6 class="${className}">${content}</h6>`,
  p: (content, className) => `<p class="${className}">${content}</p>`,
  a: (content, href, className) => `<a href="${href}" class="${className}">${content}</a>`,
  img: (src, alt, className) => `<img src="${src}" alt="${alt}" class="${className}">`,
  button: (content, className) => `<button class="${className}">${content}</button>`,
  unorderedList: (items, className) => `<ul class="${className}">${items.map(item => `<li>${item}</li>`).join('')}</ul>`,
  orderedList: (items, className) => `<ol class="${className}">${items.map(item => `<li>${item}</li>`).join('')}</ol>`,
}